# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import flux_pb2 as flux__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in flux_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FluxServiceStub(object):
    """Service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
            "/flux.FluxService/Submit",
            request_serializer=flux__pb2.SubmitRequest.SerializeToString,
            response_deserializer=flux__pb2.SubmitResponse.FromString,
            _registered_method=True,
        )
        self.Jobs = channel.unary_unary(
            "/flux.FluxService/Jobs",
            request_serializer=flux__pb2.JobsRequest.SerializeToString,
            response_deserializer=flux__pb2.JobsResponse.FromString,
            _registered_method=True,
        )


class FluxServiceServicer(object):
    """Service definition"""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Jobs(self, request, context):
        """rpc Info(InfoRequest) returns (InfoResponse) {}"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FluxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Submit": grpc.unary_unary_rpc_method_handler(
            servicer.Submit,
            request_deserializer=flux__pb2.SubmitRequest.FromString,
            response_serializer=flux__pb2.SubmitResponse.SerializeToString,
        ),
        "Jobs": grpc.unary_unary_rpc_method_handler(
            servicer.Jobs,
            request_deserializer=flux__pb2.JobsRequest.FromString,
            response_serializer=flux__pb2.JobsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("flux.FluxService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("flux.FluxService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FluxService(object):
    """Service definition"""

    @staticmethod
    def Submit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flux.FluxService/Submit",
            flux__pb2.SubmitRequest.SerializeToString,
            flux__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Jobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flux.FluxService/Jobs",
            flux__pb2.JobsRequest.SerializeToString,
            flux__pb2.JobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
