// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 25 Mar 2023 12:25:31 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <flux/security/sign.h>
#include <flux/idset.h>
#include <flux/hostlist.h>
#include <stddef.h>
#include <jansson.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1
