// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/flux-grpc/flux.proto

package flux_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FluxServiceClient is the client API for FluxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FluxServiceClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// rpc Info(InfoRequest) returns (InfoResponse) {}
	Jobs(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (*JobsResponse, error)
}

type fluxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFluxServiceClient(cc grpc.ClientConnInterface) FluxServiceClient {
	return &fluxServiceClient{cc}
}

func (c *fluxServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, "/flux.FluxService/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxServiceClient) Jobs(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (*JobsResponse, error) {
	out := new(JobsResponse)
	err := c.cc.Invoke(ctx, "/flux.FluxService/Jobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FluxServiceServer is the server API for FluxService service.
// All implementations must embed UnimplementedFluxServiceServer
// for forward compatibility
type FluxServiceServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	// rpc Info(InfoRequest) returns (InfoResponse) {}
	Jobs(context.Context, *JobsRequest) (*JobsResponse, error)
	mustEmbedUnimplementedFluxServiceServer()
}

// UnimplementedFluxServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFluxServiceServer struct {
}

func (UnimplementedFluxServiceServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedFluxServiceServer) Jobs(context.Context, *JobsRequest) (*JobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Jobs not implemented")
}
func (UnimplementedFluxServiceServer) mustEmbedUnimplementedFluxServiceServer() {}

// UnsafeFluxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FluxServiceServer will
// result in compilation errors.
type UnsafeFluxServiceServer interface {
	mustEmbedUnimplementedFluxServiceServer()
}

func RegisterFluxServiceServer(s grpc.ServiceRegistrar, srv FluxServiceServer) {
	s.RegisterService(&FluxService_ServiceDesc, srv)
}

func _FluxService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.FluxService/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FluxService_Jobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServiceServer).Jobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.FluxService/Jobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServiceServer).Jobs(ctx, req.(*JobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FluxService_ServiceDesc is the grpc.ServiceDesc for FluxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FluxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flux.FluxService",
	HandlerType: (*FluxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _FluxService_Submit_Handler,
		},
		{
			MethodName: "Jobs",
			Handler:    _FluxService_Jobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/flux-grpc/flux.proto",
}
