name: build docker flux-go

on:
  pull_request: []
  release:
    types: [published]
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: make and build docker containers
    strategy:
      fail-fast: false
      matrix:
        # container base and lib prefix
        tag: [["latest", "Dockerfile"],
              ["python", "python/v1/Dockerfile"]]
    env:
      container: ghcr.io/flux-framework/flux-go
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ^1.22
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container
      run: docker build -f ${{ matrix.tag[1] }} -t ${{ env.container }}:${{ matrix.tag[0] }} .

    - name: Tag Release Image
      if: (github.event_name == 'release')
      env:
        tag: ${{ matrix.tag[0] }}
      run: |
        release=${GITHUB_REF#refs/tags/}
        if [[ "${tag}" == "python" ]]; then
          release=${release}-python
        fi
        echo "Tagging and releasing ${{ env.container }}:${release}"
        docker tag ${{ env.container }}:${{ matrix.tag[0] }} ${{ env.container }}:${release}

    - name: Deploy Container
      if: (github.event_name != 'pull_request')
      run: docker push ${{ env.container }} --all-tags
